CREATE TABLE account(
    id BIGSERIAL PRIMARY KEY,
    created TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    first_name VARCHAR NOT NULL,
    last_name VARCHAR NOT NULL,
    email VARCHAR NOT NULL,
    password VARCHAR NOT NULL
)

